---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:

    - name: "install python for Ansible."
      # Your code here
      apt:
        name: 
          - python3

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: postgres
    # Add more env vars here
    - TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
    - TYPEORM_HOST: rds-postgresql-10mintutorial.cczkspj1k7ee.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: udacityuser
    - TYPEORM_PASSWORD: Cipherx990
    - TYPEORM_DATABASE: udacitydb
    - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations
    - ENVIRONMENT: "production"
    - NODE_ENV: "production"
  roles:
    # Your code here
    - configure-server