---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "starting pm2 service"    
  become: true
  shell: 
    npm install
    pm2 stop default
    pm2 start npm -- start 
    

# - name: "checkign npm service status"    
#   become: true
#   shell: 
#      pm2 describe "backend-udapeople"
#   register: command_output_npm      
# - debug: var=command_output_npm.stdout_lines
