# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
#####################################################
#  Building Frontend
#####################################################
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout 
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
#            exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
#####################################################
#  Building Backend
#####################################################
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout 
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build             
#            exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build      
#####################################################
#  Test Front end
#####################################################
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: Front-end Test
          command: |
            cd frontend
            npm install
            npm run test             
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-test     
#####################################################
#  Test Backend
#####################################################
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - restore_cache:
          keys: [backend-test]
      - run:
          name: Back-end Test
          command: |
            cd backend
            npm install
            npm run test             
      - save_cache:
          paths: [backend/node_modules]
          key: backend-test     

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  defaults:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]